-- 주소록 테이블생성
-- id varchar(100), anme varchar(100)
CREATE TABLE ADDR(
	ID VARCHAR2(100),
	NAME VARCHAR2(100)
);

-- 주소록에 컬럼추가 birth date
ALTER TABLE ADDR ADD (BIRTH DATE);

SELECT * FROM ADDR;

-- 주소록에 COMMENTS 컬럼 추가 VARCHAR(200) 기본값 'NO COMMENT'
ALTER TABLE ADDR ADD (COMMENTS VARCHAR2(200) DEFAULT 'NO COMMENT');

INSERT INTO ADDR (ID) VALUES ('id1');

-- 주소록에 COMMENTS 컬럼 삭제
ALTER TABLE ADDR DROP (COMMENTS);

-- 주소록 ID 컬럼의 크기를 1 BYTE로 변경
ALTER TABLE ADDR MODIFY ID VARCHAR(10);

-- ADDR 테이블 이름을 ADDR2로 변경
RENAME ADDR TO ADDR2;
RENAME ADDR2 TO ADDR;

-- ADDR 테이블에다가 '주소록'이라는 COMMENT 추가
COMMENT ON TABLE ADDR IS '주소록';

-- ADDR의 NAME 컬럼에 '이름'이라는 COMMENT 추가
COMMENT ON COLUMN ADDR.NAME IS '이름';


-- 강좌 테이블 생성 (SUBJECT)
-- SUBDNO 번호
-- SUBNAME 이름
-- TERM 학기 (1,2)
-- TYPE 필수 여부 CHAR (1)

DROP TABLE SUBJECT;

CREATE TABLE SUBJECT (
	SUBNO NUMBER CONSTRAINT SUBJECT_PK PRIMARY KEY,
	SUBNAME VARCHAR(200) CONSTRAINT SUBNAME_NN NOT NULL,
	TERM CHAR(1) CONSTRAINT TERM_CK CHECK (TERM IN ('1','2')),
	TYPE CHAR(1)
);

SELECT * FROM SUBJECT;

SELECT * FROM STUDENT s ;

ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY(STUDNO);

CREATE TABLE SUGANG (
	STUDNO CONSTRAINT SUGANG_STUDNO_FK REFERENCES STUDENT,
	SUBNO NUMBER,
	REGDATE DATE,
	RESULT NUMBER(3),
	CONSTRAINT SUGANG_SUBNO_FK  FOREIGN KEY(SUBNO) REFERENCES SUBJECT(SUBNO),
	CONSTRAINT SUGANG_PK PRIMARY KEY(STUDNO, SUBNO)
);

-- 학과 테이블에 제약조건 넣기
-- PK : DEPTNO, DNAME : NN, COLLEGE <> DEPTNO FK
ALTER TABLE DEPARTMENT MODIFY (DEPTNO CONSTRAINT DEPARTMENT_PK PRIMARY KEY); --제약조건 수정
ALTER TABLE DEPARTMENT MODIFY (DNAME NOT NULL);
ALTER TABLE DEPARTMENT MODIFY (COLLEGE REFERENCES DEPARTMENT(DEPTNO));

SELECT * FROM PROFESSOR p ;

-- 교수 테이블에 제약조건 넣기
-- PK, 이름 NN, 아이디 UNIQUE, FK DEPTNO
ALTER TABLE PROFESSOR ADD CONSTRAINT PROFESSOR_PK PRIMARY KEY(PROFNO);
ALTER TABLE PROFESSOR MODIFY (NAME NOT NULL);
ALTER TABLE PROFESSOR ADD CONSTRAINT PROF_USERID_UK UNIQUE(USERID);
ALTER TABLE PROFESSOR ADD FOREIGN KEY(DEPTNO) REFERENCES DEPARTMENT ; 


SELECT * FROM STUDENT;

-- 학생
-- 이름 NN, 아이디 UNIQUE, 주민번호 UNIQUE, FK DEPTNO, FK PROFNO
ALTER TABLE STUDENT MODIFY (NAME NOT NULL);
ALTER TABLE STUDENT MODIFY (USERID CONSTRAINT STUD_USERID_UK UNIQUE); --COLUMN LEVEL
ALTER TABLE STUDENT ADD CONSTRAINT STUD_IDNUM_UK UNIQUE(IDNUM);
ALTER TABLE STUDENT MODIFY (DEPTNO REFERENCES DEPARTMENT);
ALTER TABLE STUDENT ADD FOREIGN KEY(PROFNO) REFERENCES PROFESSOR;

SELECT  DISTINCT PROFNO FROM STUDENT;

SELECT PROFNO FROM PROFESSOR;