GRANT CREATE VIEW TO SAMPLE;

SELECT * FROM SAMPLE.STUDENT;

-- AUDIT 감사

-- SAMPLE이 HR의 EMPLOYEES에 셀렉트 할 수 있는 권한 부여
GRANT SELECT  
ON HR.EMPLOYEES
TO SAMPLE;

-- SAMPLE이 HR의 EMPLOOYEES에 셀렉트 할 수 있는 권한 철회
REVOKE SELECT 
ON HR.EMPLOYEES
FROM SAMPLE;

-- SAMPLE에 CREATE SYNONYM 권한 부여
GRANT CREATE PUBLIC SYNONYM
TO SAMPLE;

GRANT DBA
TO SAMPLE;

-- 권한 철회
REVOKE DBA
FROM SAMPLE;

-- STUDENT -> STU 공용 동의어 생성
CREATE PUBLIC SYNONYM STU FOR SAMPLE.STUDENT;
-- 동의어 삭제
DROP PUBLIC SYNONYM STU;